title: RHUL Buggy Racing
description: A Python programming project
theme: minima
url: https://www.example.com
aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
